// Generated by gencpp from file imu_processing/imu_request.msg
// DO NOT EDIT!


#ifndef IMU_PROCESSING_MESSAGE_IMU_REQUEST_H
#define IMU_PROCESSING_MESSAGE_IMU_REQUEST_H

#include <ros/service_traits.h>


#include <imu_processing/imu_requestRequest.h>
#include <imu_processing/imu_requestResponse.h>


namespace imu_processing
{

struct imu_request
{

typedef imu_requestRequest Request;
typedef imu_requestResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct imu_request
} // namespace imu_processing


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::imu_processing::imu_request > {
  static const char* value()
  {
    return "f62e73a8860f1669122b98088d03237c";
  }

  static const char* value(const ::imu_processing::imu_request&) { return value(); }
};

template<>
struct DataType< ::imu_processing::imu_request > {
  static const char* value()
  {
    return "imu_processing/imu_request";
  }

  static const char* value(const ::imu_processing::imu_request&) { return value(); }
};


// service_traits::MD5Sum< ::imu_processing::imu_requestRequest> should match
// service_traits::MD5Sum< ::imu_processing::imu_request >
template<>
struct MD5Sum< ::imu_processing::imu_requestRequest>
{
  static const char* value()
  {
    return MD5Sum< ::imu_processing::imu_request >::value();
  }
  static const char* value(const ::imu_processing::imu_requestRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::imu_processing::imu_requestRequest> should match
// service_traits::DataType< ::imu_processing::imu_request >
template<>
struct DataType< ::imu_processing::imu_requestRequest>
{
  static const char* value()
  {
    return DataType< ::imu_processing::imu_request >::value();
  }
  static const char* value(const ::imu_processing::imu_requestRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::imu_processing::imu_requestResponse> should match
// service_traits::MD5Sum< ::imu_processing::imu_request >
template<>
struct MD5Sum< ::imu_processing::imu_requestResponse>
{
  static const char* value()
  {
    return MD5Sum< ::imu_processing::imu_request >::value();
  }
  static const char* value(const ::imu_processing::imu_requestResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::imu_processing::imu_requestResponse> should match
// service_traits::DataType< ::imu_processing::imu_request >
template<>
struct DataType< ::imu_processing::imu_requestResponse>
{
  static const char* value()
  {
    return DataType< ::imu_processing::imu_request >::value();
  }
  static const char* value(const ::imu_processing::imu_requestResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // IMU_PROCESSING_MESSAGE_IMU_REQUEST_H
