// Generated by gencpp from file imu_processing/imu_requestResponse.msg
// DO NOT EDIT!


#ifndef IMU_PROCESSING_MESSAGE_IMU_REQUESTRESPONSE_H
#define IMU_PROCESSING_MESSAGE_IMU_REQUESTRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace imu_processing
{
template <class ContainerAllocator>
struct imu_requestResponse_
{
  typedef imu_requestResponse_<ContainerAllocator> Type;

  imu_requestResponse_()
    : calibrated(false)  {
    }
  imu_requestResponse_(const ContainerAllocator& _alloc)
    : calibrated(false)  {
  (void)_alloc;
    }



   typedef uint8_t _calibrated_type;
  _calibrated_type calibrated;





  typedef boost::shared_ptr< ::imu_processing::imu_requestResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::imu_processing::imu_requestResponse_<ContainerAllocator> const> ConstPtr;

}; // struct imu_requestResponse_

typedef ::imu_processing::imu_requestResponse_<std::allocator<void> > imu_requestResponse;

typedef boost::shared_ptr< ::imu_processing::imu_requestResponse > imu_requestResponsePtr;
typedef boost::shared_ptr< ::imu_processing::imu_requestResponse const> imu_requestResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::imu_processing::imu_requestResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::imu_processing::imu_requestResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::imu_processing::imu_requestResponse_<ContainerAllocator1> & lhs, const ::imu_processing::imu_requestResponse_<ContainerAllocator2> & rhs)
{
  return lhs.calibrated == rhs.calibrated;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::imu_processing::imu_requestResponse_<ContainerAllocator1> & lhs, const ::imu_processing::imu_requestResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace imu_processing

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::imu_processing::imu_requestResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::imu_processing::imu_requestResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::imu_processing::imu_requestResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::imu_processing::imu_requestResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::imu_processing::imu_requestResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::imu_processing::imu_requestResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::imu_processing::imu_requestResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "57ce5b1e5005f046a42a167a2178463c";
  }

  static const char* value(const ::imu_processing::imu_requestResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x57ce5b1e5005f046ULL;
  static const uint64_t static_value2 = 0xa42a167a2178463cULL;
};

template<class ContainerAllocator>
struct DataType< ::imu_processing::imu_requestResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "imu_processing/imu_requestResponse";
  }

  static const char* value(const ::imu_processing::imu_requestResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::imu_processing::imu_requestResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool calibrated\n"
"\n"
;
  }

  static const char* value(const ::imu_processing::imu_requestResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::imu_processing::imu_requestResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.calibrated);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct imu_requestResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::imu_processing::imu_requestResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::imu_processing::imu_requestResponse_<ContainerAllocator>& v)
  {
    s << indent << "calibrated: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.calibrated);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IMU_PROCESSING_MESSAGE_IMU_REQUESTRESPONSE_H
