// Generated by gencpp from file imu_processing/imu_requestRequest.msg
// DO NOT EDIT!


#ifndef IMU_PROCESSING_MESSAGE_IMU_REQUESTREQUEST_H
#define IMU_PROCESSING_MESSAGE_IMU_REQUESTREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace imu_processing
{
template <class ContainerAllocator>
struct imu_requestRequest_
{
  typedef imu_requestRequest_<ContainerAllocator> Type;

  imu_requestRequest_()
    : calibrate(false)
    , start_conversion(false)
    , isCalibrated(false)  {
    }
  imu_requestRequest_(const ContainerAllocator& _alloc)
    : calibrate(false)
    , start_conversion(false)
    , isCalibrated(false)  {
  (void)_alloc;
    }



   typedef uint8_t _calibrate_type;
  _calibrate_type calibrate;

   typedef uint8_t _start_conversion_type;
  _start_conversion_type start_conversion;

   typedef uint8_t _isCalibrated_type;
  _isCalibrated_type isCalibrated;





  typedef boost::shared_ptr< ::imu_processing::imu_requestRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::imu_processing::imu_requestRequest_<ContainerAllocator> const> ConstPtr;

}; // struct imu_requestRequest_

typedef ::imu_processing::imu_requestRequest_<std::allocator<void> > imu_requestRequest;

typedef boost::shared_ptr< ::imu_processing::imu_requestRequest > imu_requestRequestPtr;
typedef boost::shared_ptr< ::imu_processing::imu_requestRequest const> imu_requestRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::imu_processing::imu_requestRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::imu_processing::imu_requestRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::imu_processing::imu_requestRequest_<ContainerAllocator1> & lhs, const ::imu_processing::imu_requestRequest_<ContainerAllocator2> & rhs)
{
  return lhs.calibrate == rhs.calibrate &&
    lhs.start_conversion == rhs.start_conversion &&
    lhs.isCalibrated == rhs.isCalibrated;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::imu_processing::imu_requestRequest_<ContainerAllocator1> & lhs, const ::imu_processing::imu_requestRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace imu_processing

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::imu_processing::imu_requestRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::imu_processing::imu_requestRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::imu_processing::imu_requestRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::imu_processing::imu_requestRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::imu_processing::imu_requestRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::imu_processing::imu_requestRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::imu_processing::imu_requestRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0f813b7b5dae5791c52992bacb5a1150";
  }

  static const char* value(const ::imu_processing::imu_requestRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0f813b7b5dae5791ULL;
  static const uint64_t static_value2 = 0xc52992bacb5a1150ULL;
};

template<class ContainerAllocator>
struct DataType< ::imu_processing::imu_requestRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "imu_processing/imu_requestRequest";
  }

  static const char* value(const ::imu_processing::imu_requestRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::imu_processing::imu_requestRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool calibrate\n"
"bool start_conversion\n"
"bool isCalibrated\n"
;
  }

  static const char* value(const ::imu_processing::imu_requestRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::imu_processing::imu_requestRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.calibrate);
      stream.next(m.start_conversion);
      stream.next(m.isCalibrated);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct imu_requestRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::imu_processing::imu_requestRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::imu_processing::imu_requestRequest_<ContainerAllocator>& v)
  {
    s << indent << "calibrate: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.calibrate);
    s << indent << "start_conversion: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.start_conversion);
    s << indent << "isCalibrated: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.isCalibrated);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IMU_PROCESSING_MESSAGE_IMU_REQUESTREQUEST_H
