// Generated by gencpp from file pose_est/pose_est_msg.msg
// DO NOT EDIT!


#ifndef POSE_EST_MESSAGE_POSE_EST_MSG_H
#define POSE_EST_MESSAGE_POSE_EST_MSG_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Point.h>

namespace pose_est
{
template <class ContainerAllocator>
struct pose_est_msg_
{
  typedef pose_est_msg_<ContainerAllocator> Type;

  pose_est_msg_()
    : header()
    , name()
    , id(0)
    , point()  {
    }
  pose_est_msg_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , name(_alloc)
    , id(0)
    , point(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _name_type;
  _name_type name;

   typedef int32_t _id_type;
  _id_type id;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _point_type;
  _point_type point;





  typedef boost::shared_ptr< ::pose_est::pose_est_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pose_est::pose_est_msg_<ContainerAllocator> const> ConstPtr;

}; // struct pose_est_msg_

typedef ::pose_est::pose_est_msg_<std::allocator<void> > pose_est_msg;

typedef boost::shared_ptr< ::pose_est::pose_est_msg > pose_est_msgPtr;
typedef boost::shared_ptr< ::pose_est::pose_est_msg const> pose_est_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pose_est::pose_est_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pose_est::pose_est_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pose_est::pose_est_msg_<ContainerAllocator1> & lhs, const ::pose_est::pose_est_msg_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.name == rhs.name &&
    lhs.id == rhs.id &&
    lhs.point == rhs.point;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pose_est::pose_est_msg_<ContainerAllocator1> & lhs, const ::pose_est::pose_est_msg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pose_est

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::pose_est::pose_est_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pose_est::pose_est_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pose_est::pose_est_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pose_est::pose_est_msg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pose_est::pose_est_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pose_est::pose_est_msg_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pose_est::pose_est_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "08fd9b71ae659c640c4aa0550e3db897";
  }

  static const char* value(const ::pose_est::pose_est_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x08fd9b71ae659c64ULL;
  static const uint64_t static_value2 = 0x0c4aa0550e3db897ULL;
};

template<class ContainerAllocator>
struct DataType< ::pose_est::pose_est_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pose_est/pose_est_msg";
  }

  static const char* value(const ::pose_est::pose_est_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pose_est::pose_est_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"string name\n"
"int32 id\n"
"geometry_msgs/Point point\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::pose_est::pose_est_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pose_est::pose_est_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.name);
      stream.next(m.id);
      stream.next(m.point);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct pose_est_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pose_est::pose_est_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pose_est::pose_est_msg_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.name);
    s << indent << "id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.id);
    s << indent << "point: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.point);
  }
};

} // namespace message_operations
} // namespace ros

#endif // POSE_EST_MESSAGE_POSE_EST_MSG_H
