// Generated by gencpp from file base_link/start_carResponse.msg
// DO NOT EDIT!


#ifndef BASE_LINK_MESSAGE_START_CARRESPONSE_H
#define BASE_LINK_MESSAGE_START_CARRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace base_link
{
template <class ContainerAllocator>
struct start_carResponse_
{
  typedef start_carResponse_<ContainerAllocator> Type;

  start_carResponse_()
    {
    }
  start_carResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::base_link::start_carResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::base_link::start_carResponse_<ContainerAllocator> const> ConstPtr;

}; // struct start_carResponse_

typedef ::base_link::start_carResponse_<std::allocator<void> > start_carResponse;

typedef boost::shared_ptr< ::base_link::start_carResponse > start_carResponsePtr;
typedef boost::shared_ptr< ::base_link::start_carResponse const> start_carResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::base_link::start_carResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::base_link::start_carResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace base_link

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::base_link::start_carResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::base_link::start_carResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::base_link::start_carResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::base_link::start_carResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::base_link::start_carResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::base_link::start_carResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::base_link::start_carResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::base_link::start_carResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::base_link::start_carResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "base_link/start_carResponse";
  }

  static const char* value(const ::base_link::start_carResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::base_link::start_carResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::base_link::start_carResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::base_link::start_carResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct start_carResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::base_link::start_carResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::base_link::start_carResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // BASE_LINK_MESSAGE_START_CARRESPONSE_H
