// Generated by gencpp from file base_link/start_carRequest.msg
// DO NOT EDIT!


#ifndef BASE_LINK_MESSAGE_START_CARREQUEST_H
#define BASE_LINK_MESSAGE_START_CARREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace base_link
{
template <class ContainerAllocator>
struct start_carRequest_
{
  typedef start_carRequest_<ContainerAllocator> Type;

  start_carRequest_()
    : start(false)
    , reset(false)  {
    }
  start_carRequest_(const ContainerAllocator& _alloc)
    : start(false)
    , reset(false)  {
  (void)_alloc;
    }



   typedef uint8_t _start_type;
  _start_type start;

   typedef uint8_t _reset_type;
  _reset_type reset;





  typedef boost::shared_ptr< ::base_link::start_carRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::base_link::start_carRequest_<ContainerAllocator> const> ConstPtr;

}; // struct start_carRequest_

typedef ::base_link::start_carRequest_<std::allocator<void> > start_carRequest;

typedef boost::shared_ptr< ::base_link::start_carRequest > start_carRequestPtr;
typedef boost::shared_ptr< ::base_link::start_carRequest const> start_carRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::base_link::start_carRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::base_link::start_carRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::base_link::start_carRequest_<ContainerAllocator1> & lhs, const ::base_link::start_carRequest_<ContainerAllocator2> & rhs)
{
  return lhs.start == rhs.start &&
    lhs.reset == rhs.reset;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::base_link::start_carRequest_<ContainerAllocator1> & lhs, const ::base_link::start_carRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace base_link

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::base_link::start_carRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::base_link::start_carRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::base_link::start_carRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::base_link::start_carRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::base_link::start_carRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::base_link::start_carRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::base_link::start_carRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "25b7112e38c3a73795d5458eaa302398";
  }

  static const char* value(const ::base_link::start_carRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x25b7112e38c3a737ULL;
  static const uint64_t static_value2 = 0x95d5458eaa302398ULL;
};

template<class ContainerAllocator>
struct DataType< ::base_link::start_carRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "base_link/start_carRequest";
  }

  static const char* value(const ::base_link::start_carRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::base_link::start_carRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool start\n"
"bool reset\n"
;
  }

  static const char* value(const ::base_link::start_carRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::base_link::start_carRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.start);
      stream.next(m.reset);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct start_carRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::base_link::start_carRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::base_link::start_carRequest_<ContainerAllocator>& v)
  {
    s << indent << "start: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.start);
    s << indent << "reset: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.reset);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BASE_LINK_MESSAGE_START_CARREQUEST_H
