// Generated by gencpp from file base_link/start_car.msg
// DO NOT EDIT!


#ifndef BASE_LINK_MESSAGE_START_CAR_H
#define BASE_LINK_MESSAGE_START_CAR_H

#include <ros/service_traits.h>


#include <base_link/start_carRequest.h>
#include <base_link/start_carResponse.h>


namespace base_link
{

struct start_car
{

typedef start_carRequest Request;
typedef start_carResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct start_car
} // namespace base_link


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::base_link::start_car > {
  static const char* value()
  {
    return "25b7112e38c3a73795d5458eaa302398";
  }

  static const char* value(const ::base_link::start_car&) { return value(); }
};

template<>
struct DataType< ::base_link::start_car > {
  static const char* value()
  {
    return "base_link/start_car";
  }

  static const char* value(const ::base_link::start_car&) { return value(); }
};


// service_traits::MD5Sum< ::base_link::start_carRequest> should match
// service_traits::MD5Sum< ::base_link::start_car >
template<>
struct MD5Sum< ::base_link::start_carRequest>
{
  static const char* value()
  {
    return MD5Sum< ::base_link::start_car >::value();
  }
  static const char* value(const ::base_link::start_carRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::base_link::start_carRequest> should match
// service_traits::DataType< ::base_link::start_car >
template<>
struct DataType< ::base_link::start_carRequest>
{
  static const char* value()
  {
    return DataType< ::base_link::start_car >::value();
  }
  static const char* value(const ::base_link::start_carRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::base_link::start_carResponse> should match
// service_traits::MD5Sum< ::base_link::start_car >
template<>
struct MD5Sum< ::base_link::start_carResponse>
{
  static const char* value()
  {
    return MD5Sum< ::base_link::start_car >::value();
  }
  static const char* value(const ::base_link::start_carResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::base_link::start_carResponse> should match
// service_traits::DataType< ::base_link::start_car >
template<>
struct DataType< ::base_link::start_carResponse>
{
  static const char* value()
  {
    return DataType< ::base_link::start_car >::value();
  }
  static const char* value(const ::base_link::start_carResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BASE_LINK_MESSAGE_START_CAR_H
