// Generated by gencpp from file mecanum_ik/vector4_msg.msg
// DO NOT EDIT!


#ifndef MECANUM_IK_MESSAGE_VECTOR4_MSG_H
#define MECANUM_IK_MESSAGE_VECTOR4_MSG_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mecanum_ik
{
template <class ContainerAllocator>
struct vector4_msg_
{
  typedef vector4_msg_<ContainerAllocator> Type;

  vector4_msg_()
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , w(0.0)  {
    }
  vector4_msg_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , w(0.0)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _z_type;
  _z_type z;

   typedef double _w_type;
  _w_type w;





  typedef boost::shared_ptr< ::mecanum_ik::vector4_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mecanum_ik::vector4_msg_<ContainerAllocator> const> ConstPtr;

}; // struct vector4_msg_

typedef ::mecanum_ik::vector4_msg_<std::allocator<void> > vector4_msg;

typedef boost::shared_ptr< ::mecanum_ik::vector4_msg > vector4_msgPtr;
typedef boost::shared_ptr< ::mecanum_ik::vector4_msg const> vector4_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mecanum_ik::vector4_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mecanum_ik::vector4_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mecanum_ik::vector4_msg_<ContainerAllocator1> & lhs, const ::mecanum_ik::vector4_msg_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z &&
    lhs.w == rhs.w;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mecanum_ik::vector4_msg_<ContainerAllocator1> & lhs, const ::mecanum_ik::vector4_msg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mecanum_ik

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mecanum_ik::vector4_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mecanum_ik::vector4_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mecanum_ik::vector4_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mecanum_ik::vector4_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mecanum_ik::vector4_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mecanum_ik::vector4_msg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mecanum_ik::vector4_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a779879fadf0160734f906b8c19c7004";
  }

  static const char* value(const ::mecanum_ik::vector4_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa779879fadf01607ULL;
  static const uint64_t static_value2 = 0x34f906b8c19c7004ULL;
};

template<class ContainerAllocator>
struct DataType< ::mecanum_ik::vector4_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mecanum_ik/vector4_msg";
  }

  static const char* value(const ::mecanum_ik::vector4_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mecanum_ik::vector4_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::mecanum_ik::vector4_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mecanum_ik::vector4_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.w);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct vector4_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mecanum_ik::vector4_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mecanum_ik::vector4_msg_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
    s << indent << "w: ";
    Printer<double>::stream(s, indent + "  ", v.w);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MECANUM_IK_MESSAGE_VECTOR4_MSG_H
